### ISSUE TITLE
Price rises are cumulative on a GW basis

### ISSUE THREAD

**Issue by jamiebarker0310** [amosbastian/FPLbot#17]
Jimenez is a prime example for this GW - he rose just after the deadline and since his suspension has dropped back. The price for the drop back then shows as 0.0 rather than -0.1. Would it be possible to add a column that shows the daily change rather than the cumulative GW Change?

**Comment by amosbastian** [comment]
Daily price change can only be -0.1 and he was in the fallers list, so I don't think adding a column for that is necessary since it should be clear enough imo. It also says at the bottom that `∆ = price change this gameweek`, not day.
