### ISSUE TITLE
Stack the player comparison tables

### ISSUE THREAD

**Issue by amosbastian** [amosbastian/FPLbot#5]
From [/u/Myfantasyredditacct](https://www.reddit.com/user/Myfantasyredditacct):

>This is really great work.
>
>My suggestion would be if you could stack the player comparison tables.  Currently it is not >mobile friendly.
>
>So possibly this:
>
>## Son (£8.9) vs. Mané (£9.6) (last 2 fixtures)
>
>## Son
>
>|G|xG|A|xA|MP|Fixture|
>|:-|:-|:-|:-|:-|:-|
>|1|0.42|0|0.13|90|Spurs 3-1 Leicester|
>|1|0.19|0|0.7|90|Spurs 1-0 Newcastle United|
>|**2**|**0.61**|**0**|**0.83**|**180**||
>
>## Mané
>
>|G|xG|A|xA|MP|Fixtures|
>|:-|:-|:-|:-|:-|:-|
>|1|0.58|0|0.12|89|Liverpool 3-0 Bournemouth|
>|1|0.64|0|0|90|West Ham 1-1 Liverpool|
>|**2**|**1.22**|**0**|**0.12**|**179**||

https://www.reddit.com/r/FantasyPL/comments/b9r754/updating_adding_new_features_to_fantasypl_bot/ek6hgq3/?context=3

**Comment by spinach** [comment]
Thanks a lot for your work mate! Just here to say +1 on this, the format is much easier to read and more natural, + would work on mobile.
